// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreFrame.Infrastructure;

namespace NetCoreFrame.Infrastructure.Migrations.WorkFlowDb
{
    [DbContext(typeof(WorkFlowDbContext))]
    partial class WorkFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnName("SourceId")
                        .HasMaxLength(50);

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnName("TargetId")
                        .HasMaxLength(50);

                    b.Property<Guid>("WorkFlowSettingID")
                        .HasColumnName("WorkFlowSettingID");

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowConnection");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("EndpointText")
                        .IsRequired()
                        .HasColumnName("EndpointText")
                        .HasMaxLength(50);

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasColumnName("EndpointType")
                        .HasMaxLength(20);

                    b.Property<int?>("OffsetLeft")
                        .IsRequired()
                        .HasColumnName("OffsetLeft");

                    b.Property<int?>("OffsetTop")
                        .IsRequired()
                        .HasColumnName("OffsetTop");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnName("UID")
                        .HasMaxLength(50);

                    b.Property<Guid>("WorkFlowSettingID")
                        .HasColumnName("WorkFlowSettingID")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowEndpoint");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnName("CreatorUserId");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("FlowRoleName")
                        .IsRequired()
                        .HasColumnName("FlowRoleName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnName("LastModifierUserId");

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowRole");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowRoleToUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid>("FlowRoleID")
                        .HasColumnName("FlowRoleID");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowRoleToUser");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnName("CreatorUserId");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnName("LastModifierUserId");

                    b.Property<string>("WorkFlowName")
                        .IsRequired()
                        .HasColumnName("WorkFlowName")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowSetting");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnName("CreatorUserId");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("FlowTypeName")
                        .IsRequired()
                        .HasColumnName("FlowTypeName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnName("IsReadOnly");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnName("LastModifierUserId");

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowType");
                });
#pragma warning restore 612, 618
        }
    }
}
