// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreFrame.Infrastructure;

namespace NetCoreFrame.Infrastructure.Migrations
{
    [DbContext(typeof(WorkFlowDbContext))]
    partial class WorkFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("WorkFlowSettingID");

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowConnection");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("EndpointText")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("OffsetLeft")
                        .IsRequired();

                    b.Property<int?>("OffsetTop")
                        .IsRequired();

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("WorkFlowSettingID")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowEndpoint");
                });

            modelBuilder.Entity("NetCoreWorkFlow.Core.SysWorkFlowSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnName("CreatorUserId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnName("LastModifierUserId");

                    b.Property<string>("WorkFlowName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
